services:
  redis:
    image: redis:7
    container_name: redis_chat
    ports:
      - '6379:6379'
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
  backend:
    build: ./backend
    container_name: chat_backend
    ports:
      - '4000:4000'
    depends_on:
      - redis
      - postgres
      - mqtt
    command: sh -c "npx prisma db push && npx prisma generate && npm run ts"

  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  postgres_data:
