services:
  redis:
    image: redis:7
    container_name: redis_chat
    ports:
      - '6379:6379'
  postgres:
    image: postgres:15
    container_name: postgres_chat
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: chat_backend
    ports:
      - '4000:4000'
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
volumes:
  postgres_data:
