module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/test'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.{ts,js}',
    '!src/generated/**',
    '!src/config/envs.ts',
    '!src/config/openai.ts',
    '!src/config/mqtt.ts',
    '!src/config/db.ts',
    '!src/index.ts',
    '!src/routes/index.ts',
    '!src/routes/router.ts',
    '!src/generated/**',
    '!src/prisma/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/build/',
    '/coverage/',
    '/__mocks__/',
    'index\\.ts$',
  ],
  coveragePathIgnorePatterns: ['index\\.ts$'],
};
